/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletTransactionStatusRouteImport } from './routes/wallet-transaction-status'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as TennisRouteImport } from './routes/tennis'
import { Route as NewsRouteImport } from './routes/news'
import { Route as GamesRouteImport } from './routes/games'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as BettingRouteImport } from './routes/betting'
import { Route as BasketballRouteImport } from './routes/basketball'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TennisIndexRouteImport } from './routes/tennis.index'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as BasketballIndexRouteImport } from './routes/basketball.index'
import { Route as TennisIdRouteImport } from './routes/tennis/$Id'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as IndexGameIdRouteImport } from './routes/index.$gameId'
import { Route as BasketballIdRouteImport } from './routes/basketball/$Id'
import { Route as AuthorsSlugRouteImport } from './routes/authors.$slug'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthLayoutRouteImport } from './routes/auth/_layout'
import { Route as NewsSlugOgRouteImport } from './routes/news.$slug.og'
import { Route as IndexTournamentTournamentIdRouteImport } from './routes/index.tournament.$tournamentId'
import { Route as BasketballTournamentTournamentIdRouteImport } from './routes/basketball.tournament.$tournamentId'

const WalletTransactionStatusRoute = WalletTransactionStatusRouteImport.update({
  id: '/wallet-transaction-status',
  path: '/wallet-transaction-status',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const TennisRoute = TennisRouteImport.update({
  id: '/tennis',
  path: '/tennis',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const BettingRoute = BettingRouteImport.update({
  id: '/betting',
  path: '/betting',
  getParentRoute: () => rootRouteImport,
} as any)
const BasketballRoute = BasketballRouteImport.update({
  id: '/basketball',
  path: '/basketball',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TennisIndexRoute = TennisIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TennisRoute,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NewsRoute,
} as any)
const BasketballIndexRoute = BasketballIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BasketballRoute,
} as any)
const TennisIdRoute = TennisIdRouteImport.update({
  id: '/$Id',
  path: '/$Id',
  getParentRoute: () => TennisRoute,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NewsRoute,
} as any)
const IndexGameIdRoute = IndexGameIdRouteImport.update({
  id: '/index/$gameId',
  path: '/index/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const BasketballIdRoute = BasketballIdRouteImport.update({
  id: '/$Id',
  path: '/$Id',
  getParentRoute: () => BasketballRoute,
} as any)
const AuthorsSlugRoute = AuthorsSlugRouteImport.update({
  id: '/authors/$slug',
  path: '/authors/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/auth/_layout',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugOgRoute = NewsSlugOgRouteImport.update({
  id: '/og',
  path: '/og',
  getParentRoute: () => NewsSlugRoute,
} as any)
const IndexTournamentTournamentIdRoute =
  IndexTournamentTournamentIdRouteImport.update({
    id: '/index/tournament/$tournamentId',
    path: '/index/tournament/$tournamentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const BasketballTournamentTournamentIdRoute =
  BasketballTournamentTournamentIdRouteImport.update({
    id: '/tournament/$tournamentId',
    path: '/tournament/$tournamentId',
    getParentRoute: () => BasketballRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/basketball': typeof BasketballRouteWithChildren
  '/betting': typeof BettingRoute
  '/favorites': typeof FavoritesRoute
  '/games': typeof GamesRoute
  '/news': typeof NewsRouteWithChildren
  '/tennis': typeof TennisRouteWithChildren
  '/wallet': typeof WalletRoute
  '/wallet-transaction-status': typeof WalletTransactionStatusRoute
  '/auth': typeof AuthLayoutRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/authors/$slug': typeof AuthorsSlugRoute
  '/basketball/$Id': typeof BasketballIdRoute
  '/index/$gameId': typeof IndexGameIdRoute
  '/news/$slug': typeof NewsSlugRouteWithChildren
  '/tennis/$Id': typeof TennisIdRoute
  '/basketball/': typeof BasketballIndexRoute
  '/news/': typeof NewsIndexRoute
  '/tennis/': typeof TennisIndexRoute
  '/basketball/tournament/$tournamentId': typeof BasketballTournamentTournamentIdRoute
  '/index/tournament/$tournamentId': typeof IndexTournamentTournamentIdRoute
  '/news/$slug/og': typeof NewsSlugOgRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/betting': typeof BettingRoute
  '/favorites': typeof FavoritesRoute
  '/games': typeof GamesRoute
  '/wallet': typeof WalletRoute
  '/wallet-transaction-status': typeof WalletTransactionStatusRoute
  '/auth': typeof AuthLayoutRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/authors/$slug': typeof AuthorsSlugRoute
  '/basketball/$Id': typeof BasketballIdRoute
  '/index/$gameId': typeof IndexGameIdRoute
  '/news/$slug': typeof NewsSlugRouteWithChildren
  '/tennis/$Id': typeof TennisIdRoute
  '/basketball': typeof BasketballIndexRoute
  '/news': typeof NewsIndexRoute
  '/tennis': typeof TennisIndexRoute
  '/basketball/tournament/$tournamentId': typeof BasketballTournamentTournamentIdRoute
  '/index/tournament/$tournamentId': typeof IndexTournamentTournamentIdRoute
  '/news/$slug/og': typeof NewsSlugOgRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/basketball': typeof BasketballRouteWithChildren
  '/betting': typeof BettingRoute
  '/favorites': typeof FavoritesRoute
  '/games': typeof GamesRoute
  '/news': typeof NewsRouteWithChildren
  '/tennis': typeof TennisRouteWithChildren
  '/wallet': typeof WalletRoute
  '/wallet-transaction-status': typeof WalletTransactionStatusRoute
  '/auth/_layout': typeof AuthLayoutRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/authors/$slug': typeof AuthorsSlugRoute
  '/basketball/$Id': typeof BasketballIdRoute
  '/index/$gameId': typeof IndexGameIdRoute
  '/news/$slug': typeof NewsSlugRouteWithChildren
  '/tennis/$Id': typeof TennisIdRoute
  '/basketball/': typeof BasketballIndexRoute
  '/news/': typeof NewsIndexRoute
  '/tennis/': typeof TennisIndexRoute
  '/basketball/tournament/$tournamentId': typeof BasketballTournamentTournamentIdRoute
  '/index/tournament/$tournamentId': typeof IndexTournamentTournamentIdRoute
  '/news/$slug/og': typeof NewsSlugOgRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/basketball'
    | '/betting'
    | '/favorites'
    | '/games'
    | '/news'
    | '/tennis'
    | '/wallet'
    | '/wallet-transaction-status'
    | '/auth'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/authors/$slug'
    | '/basketball/$Id'
    | '/index/$gameId'
    | '/news/$slug'
    | '/tennis/$Id'
    | '/basketball/'
    | '/news/'
    | '/tennis/'
    | '/basketball/tournament/$tournamentId'
    | '/index/tournament/$tournamentId'
    | '/news/$slug/og'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/betting'
    | '/favorites'
    | '/games'
    | '/wallet'
    | '/wallet-transaction-status'
    | '/auth'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/authors/$slug'
    | '/basketball/$Id'
    | '/index/$gameId'
    | '/news/$slug'
    | '/tennis/$Id'
    | '/basketball'
    | '/news'
    | '/tennis'
    | '/basketball/tournament/$tournamentId'
    | '/index/tournament/$tournamentId'
    | '/news/$slug/og'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/basketball'
    | '/betting'
    | '/favorites'
    | '/games'
    | '/news'
    | '/tennis'
    | '/wallet'
    | '/wallet-transaction-status'
    | '/auth/_layout'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/authors/$slug'
    | '/basketball/$Id'
    | '/index/$gameId'
    | '/news/$slug'
    | '/tennis/$Id'
    | '/basketball/'
    | '/news/'
    | '/tennis/'
    | '/basketball/tournament/$tournamentId'
    | '/index/tournament/$tournamentId'
    | '/news/$slug/og'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  BasketballRoute: typeof BasketballRouteWithChildren
  BettingRoute: typeof BettingRoute
  FavoritesRoute: typeof FavoritesRoute
  GamesRoute: typeof GamesRoute
  NewsRoute: typeof NewsRouteWithChildren
  TennisRoute: typeof TennisRouteWithChildren
  WalletRoute: typeof WalletRoute
  WalletTransactionStatusRoute: typeof WalletTransactionStatusRoute
  AuthLayoutRoute: typeof AuthLayoutRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthorsSlugRoute: typeof AuthorsSlugRoute
  IndexGameIdRoute: typeof IndexGameIdRoute
  IndexTournamentTournamentIdRoute: typeof IndexTournamentTournamentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet-transaction-status': {
      id: '/wallet-transaction-status'
      path: '/wallet-transaction-status'
      fullPath: '/wallet-transaction-status'
      preLoaderRoute: typeof WalletTransactionStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tennis': {
      id: '/tennis'
      path: '/tennis'
      fullPath: '/tennis'
      preLoaderRoute: typeof TennisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/betting': {
      id: '/betting'
      path: '/betting'
      fullPath: '/betting'
      preLoaderRoute: typeof BettingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basketball': {
      id: '/basketball'
      path: '/basketball'
      fullPath: '/basketball'
      preLoaderRoute: typeof BasketballRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tennis/': {
      id: '/tennis/'
      path: '/'
      fullPath: '/tennis/'
      preLoaderRoute: typeof TennisIndexRouteImport
      parentRoute: typeof TennisRoute
    }
    '/news/': {
      id: '/news/'
      path: '/'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof NewsRoute
    }
    '/basketball/': {
      id: '/basketball/'
      path: '/'
      fullPath: '/basketball/'
      preLoaderRoute: typeof BasketballIndexRouteImport
      parentRoute: typeof BasketballRoute
    }
    '/tennis/$Id': {
      id: '/tennis/$Id'
      path: '/$Id'
      fullPath: '/tennis/$Id'
      preLoaderRoute: typeof TennisIdRouteImport
      parentRoute: typeof TennisRoute
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof NewsRoute
    }
    '/index/$gameId': {
      id: '/index/$gameId'
      path: '/index/$gameId'
      fullPath: '/index/$gameId'
      preLoaderRoute: typeof IndexGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basketball/$Id': {
      id: '/basketball/$Id'
      path: '/$Id'
      fullPath: '/basketball/$Id'
      preLoaderRoute: typeof BasketballIdRouteImport
      parentRoute: typeof BasketballRoute
    }
    '/authors/$slug': {
      id: '/authors/$slug'
      path: '/authors/$slug'
      fullPath: '/authors/$slug'
      preLoaderRoute: typeof AuthorsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/_layout': {
      id: '/auth/_layout'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug/og': {
      id: '/news/$slug/og'
      path: '/og'
      fullPath: '/news/$slug/og'
      preLoaderRoute: typeof NewsSlugOgRouteImport
      parentRoute: typeof NewsSlugRoute
    }
    '/index/tournament/$tournamentId': {
      id: '/index/tournament/$tournamentId'
      path: '/index/tournament/$tournamentId'
      fullPath: '/index/tournament/$tournamentId'
      preLoaderRoute: typeof IndexTournamentTournamentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basketball/tournament/$tournamentId': {
      id: '/basketball/tournament/$tournamentId'
      path: '/tournament/$tournamentId'
      fullPath: '/basketball/tournament/$tournamentId'
      preLoaderRoute: typeof BasketballTournamentTournamentIdRouteImport
      parentRoute: typeof BasketballRoute
    }
  }
}

interface BasketballRouteChildren {
  BasketballIdRoute: typeof BasketballIdRoute
  BasketballIndexRoute: typeof BasketballIndexRoute
  BasketballTournamentTournamentIdRoute: typeof BasketballTournamentTournamentIdRoute
}

const BasketballRouteChildren: BasketballRouteChildren = {
  BasketballIdRoute: BasketballIdRoute,
  BasketballIndexRoute: BasketballIndexRoute,
  BasketballTournamentTournamentIdRoute: BasketballTournamentTournamentIdRoute,
}

const BasketballRouteWithChildren = BasketballRoute._addFileChildren(
  BasketballRouteChildren,
)

interface NewsSlugRouteChildren {
  NewsSlugOgRoute: typeof NewsSlugOgRoute
}

const NewsSlugRouteChildren: NewsSlugRouteChildren = {
  NewsSlugOgRoute: NewsSlugOgRoute,
}

const NewsSlugRouteWithChildren = NewsSlugRoute._addFileChildren(
  NewsSlugRouteChildren,
)

interface NewsRouteChildren {
  NewsSlugRoute: typeof NewsSlugRouteWithChildren
  NewsIndexRoute: typeof NewsIndexRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsSlugRoute: NewsSlugRouteWithChildren,
  NewsIndexRoute: NewsIndexRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

interface TennisRouteChildren {
  TennisIdRoute: typeof TennisIdRoute
  TennisIndexRoute: typeof TennisIndexRoute
}

const TennisRouteChildren: TennisRouteChildren = {
  TennisIdRoute: TennisIdRoute,
  TennisIndexRoute: TennisIndexRoute,
}

const TennisRouteWithChildren =
  TennisRoute._addFileChildren(TennisRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  BasketballRoute: BasketballRouteWithChildren,
  BettingRoute: BettingRoute,
  FavoritesRoute: FavoritesRoute,
  GamesRoute: GamesRoute,
  NewsRoute: NewsRouteWithChildren,
  TennisRoute: TennisRouteWithChildren,
  WalletRoute: WalletRoute,
  WalletTransactionStatusRoute: WalletTransactionStatusRoute,
  AuthLayoutRoute: AuthLayoutRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthorsSlugRoute: AuthorsSlugRoute,
  IndexGameIdRoute: IndexGameIdRoute,
  IndexTournamentTournamentIdRoute: IndexTournamentTournamentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
