/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BasketballRouteImport } from './routes/basketball'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BasketballIndexRouteImport } from './routes/basketball.index'
import { Route as BasketballIdRouteImport } from './routes/basketball/$Id'

const BasketballRoute = BasketballRouteImport.update({
  id: '/basketball',
  path: '/basketball',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BasketballIndexRoute = BasketballIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BasketballRoute,
} as any)
const BasketballIdRoute = BasketballIdRouteImport.update({
  id: '/$Id',
  path: '/$Id',
  getParentRoute: () => BasketballRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/basketball': typeof BasketballRouteWithChildren
  '/basketball/$Id': typeof BasketballIdRoute
  '/basketball/': typeof BasketballIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/basketball/$Id': typeof BasketballIdRoute
  '/basketball': typeof BasketballIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/basketball': typeof BasketballRouteWithChildren
  '/basketball/$Id': typeof BasketballIdRoute
  '/basketball/': typeof BasketballIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/basketball' | '/basketball/$Id' | '/basketball/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/basketball/$Id' | '/basketball'
  id: '__root__' | '/' | '/basketball' | '/basketball/$Id' | '/basketball/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BasketballRoute: typeof BasketballRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/basketball': {
      id: '/basketball'
      path: '/basketball'
      fullPath: '/basketball'
      preLoaderRoute: typeof BasketballRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basketball/': {
      id: '/basketball/'
      path: '/'
      fullPath: '/basketball/'
      preLoaderRoute: typeof BasketballIndexRouteImport
      parentRoute: typeof BasketballRoute
    }
    '/basketball/$Id': {
      id: '/basketball/$Id'
      path: '/$Id'
      fullPath: '/basketball/$Id'
      preLoaderRoute: typeof BasketballIdRouteImport
      parentRoute: typeof BasketballRoute
    }
  }
}

interface BasketballRouteChildren {
  BasketballIdRoute: typeof BasketballIdRoute
  BasketballIndexRoute: typeof BasketballIndexRoute
}

const BasketballRouteChildren: BasketballRouteChildren = {
  BasketballIdRoute: BasketballIdRoute,
  BasketballIndexRoute: BasketballIndexRoute,
}

const BasketballRouteWithChildren = BasketballRoute._addFileChildren(
  BasketballRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BasketballRoute: BasketballRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
