/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TennisRouteImport } from './routes/tennis'
import { Route as BasketballRouteImport } from './routes/basketball'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TennisIndexRouteImport } from './routes/tennis.index'
import { Route as BasketballIndexRouteImport } from './routes/basketball.index'
import { Route as IndexGameIdRouteImport } from './routes/index.$gameId'
import { Route as BasketballIdRouteImport } from './routes/basketball/$Id'

const TennisRoute = TennisRouteImport.update({
  id: '/tennis',
  path: '/tennis',
  getParentRoute: () => rootRouteImport,
} as any)
const BasketballRoute = BasketballRouteImport.update({
  id: '/basketball',
  path: '/basketball',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TennisIndexRoute = TennisIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TennisRoute,
} as any)
const BasketballIndexRoute = BasketballIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BasketballRoute,
} as any)
const IndexGameIdRoute = IndexGameIdRouteImport.update({
  id: '/index/$gameId',
  path: '/index/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const BasketballIdRoute = BasketballIdRouteImport.update({
  id: '/$Id',
  path: '/$Id',
  getParentRoute: () => BasketballRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/basketball': typeof BasketballRouteWithChildren
  '/tennis': typeof TennisRouteWithChildren
  '/basketball/$Id': typeof BasketballIdRoute
  '/index/$gameId': typeof IndexGameIdRoute
  '/basketball/': typeof BasketballIndexRoute
  '/tennis/': typeof TennisIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/basketball/$Id': typeof BasketballIdRoute
  '/index/$gameId': typeof IndexGameIdRoute
  '/basketball': typeof BasketballIndexRoute
  '/tennis': typeof TennisIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/basketball': typeof BasketballRouteWithChildren
  '/tennis': typeof TennisRouteWithChildren
  '/basketball/$Id': typeof BasketballIdRoute
  '/index/$gameId': typeof IndexGameIdRoute
  '/basketball/': typeof BasketballIndexRoute
  '/tennis/': typeof TennisIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/basketball'
    | '/tennis'
    | '/basketball/$Id'
    | '/index/$gameId'
    | '/basketball/'
    | '/tennis/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/basketball/$Id' | '/index/$gameId' | '/basketball' | '/tennis'
  id:
    | '__root__'
    | '/'
    | '/basketball'
    | '/tennis'
    | '/basketball/$Id'
    | '/index/$gameId'
    | '/basketball/'
    | '/tennis/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BasketballRoute: typeof BasketballRouteWithChildren
  TennisRoute: typeof TennisRouteWithChildren
  IndexGameIdRoute: typeof IndexGameIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tennis': {
      id: '/tennis'
      path: '/tennis'
      fullPath: '/tennis'
      preLoaderRoute: typeof TennisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basketball': {
      id: '/basketball'
      path: '/basketball'
      fullPath: '/basketball'
      preLoaderRoute: typeof BasketballRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tennis/': {
      id: '/tennis/'
      path: '/'
      fullPath: '/tennis/'
      preLoaderRoute: typeof TennisIndexRouteImport
      parentRoute: typeof TennisRoute
    }
    '/basketball/': {
      id: '/basketball/'
      path: '/'
      fullPath: '/basketball/'
      preLoaderRoute: typeof BasketballIndexRouteImport
      parentRoute: typeof BasketballRoute
    }
    '/index/$gameId': {
      id: '/index/$gameId'
      path: '/index/$gameId'
      fullPath: '/index/$gameId'
      preLoaderRoute: typeof IndexGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basketball/$Id': {
      id: '/basketball/$Id'
      path: '/$Id'
      fullPath: '/basketball/$Id'
      preLoaderRoute: typeof BasketballIdRouteImport
      parentRoute: typeof BasketballRoute
    }
  }
}

interface BasketballRouteChildren {
  BasketballIdRoute: typeof BasketballIdRoute
  BasketballIndexRoute: typeof BasketballIndexRoute
}

const BasketballRouteChildren: BasketballRouteChildren = {
  BasketballIdRoute: BasketballIdRoute,
  BasketballIndexRoute: BasketballIndexRoute,
}

const BasketballRouteWithChildren = BasketballRoute._addFileChildren(
  BasketballRouteChildren,
)

interface TennisRouteChildren {
  TennisIndexRoute: typeof TennisIndexRoute
}

const TennisRouteChildren: TennisRouteChildren = {
  TennisIndexRoute: TennisIndexRoute,
}

const TennisRouteWithChildren =
  TennisRoute._addFileChildren(TennisRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BasketballRoute: BasketballRouteWithChildren,
  TennisRoute: TennisRouteWithChildren,
  IndexGameIdRoute: IndexGameIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
