import DetailsImageCard from '@/shared/DetailsImageCard'
import VenueGuide from './VenueGuide'
import BasketBallScoreCard from './BasketBallScoreCard'
import type { Quarter, TeamData } from '@/types/basketball';
import { TeamStats } from './TeamStats';
import ImportantUpdate from '@/shared/ImportantUpdate';



const BasketBallDetailsPage = () => {
  const quarters: Quarter[] = [
    { id: 'q1', label: 'Q1' },
    { id: 'q2', label: 'Q2' },
    { id: 'q3', label: 'Q3' },
    { id: 'q4', label: 'Q4' }
  ];

  const team1Data: TeamData = {
    name: 'Detroit Pistons',
    quarterScores: [36, 34, 26, 25],
    total: 121,
  };

  const team2Data: TeamData = {
    name: 'Chicago Bulls',
    quarterScores: [32, 28, 26, 28],
    total: 113,
  };
  const sampleTeams = [
  {
    teamName: "Detroit Pistons",
    teamLogo: "/Pistons.png",
    starters: [
      {
        name: "Precious Achiuwa",
        number: "15",
        pts: 15,
        fg: "3-6",
        threePt: "0-2",
        ft: "2-4",
        reb: 9,
        ast: 6,
        to: 4,
        stl: 3,
        blk: 0,
        oreb: 5,
        dreb: 10,
        pf: 2,
        min: 26,
        plusMinus: -8,
      },
      {
        name: "Drew Eubanks",
        number: "15",
        pts: 15,
        fg: "3-6",
        threePt: "0-2",
        ft: "2-4",
        reb: 9,
        ast: 6,
        to: 4,
        stl: 3,
        blk: 0,
        oreb: 5,
        dreb: 10,
        pf: 2,
        min: 26,
        plusMinus: -8,
      },
      {
        name: "Russell Westbrook",
        number: "15",
        pts: 15,
        fg: "3-6",
        threePt: "0-2",
        ft: "2-4",
        reb: 9,
        ast: 6,
        to: 4,
        stl: 3,
        blk: 0,
        oreb: 5,
        dreb: 10,
        pf: 2,
        min: 26,
        plusMinus: -8,
      },
      {
        name: "DeMar DeRozan",
        number: "15",
        pts: 15,
        fg: "3-6",
        threePt: "0-2",
        ft: "2-4",
        reb: 9,
        ast: 6,
        to: 4,
        stl: 3,
        blk: 0,
        oreb: 5,
        dreb: 10,
        pf: 2,
        min: 26,
        plusMinus: -8,
      },
      {
        name: "Zach LaVine",
        number: "15",
        pts: 15,
        fg: "3-6",
        threePt: "0-2",
        ft: "2-4",
        reb: 9,
        ast: 6,
        to: 4,
        stl: 3,
        blk: 0,
        oreb: 5,
        dreb: 10,
        pf: 2,
        min: 26,
        plusMinus: -8,
      },
    ],
    bench: [
      {
        name: "Roma",
        number: "15",
        pts: 15,
        fg: "3-6",
        threePt: "0-2",
        ft: "2-4",
        reb: 9,
        ast: 8,
        to: 4,
        stl: 3,
        blk: 0,
        oreb: 5,
        dreb: 10,
        pf: 2,
        min: 26,
        plusMinus: -8,
      },
      {
        name: "Roma",
        number: "15",
        pts: 15,
        fg: "3-6",
        threePt: "0-2",
        ft: "2-4",
        reb: 9,
        ast: 8,
        to: 4,
        stl: 3,
        blk: 0,
        oreb: 5,
        dreb: 10,
        pf: 2,
        min: 26,
        plusMinus: -8,
      },
      {
        name: "Roma",
        number: "15",
        pts: 15,
        fg: "3-6",
        threePt: "0-2",
        ft: "2-4",
        reb: 9,
        ast: 8,
        to: 4,
        stl: 3,
        blk: 0,
        oreb: 5,
        dreb: 10,
        pf: 2,
        min: 26,
        plusMinus: -8,
      },
      {
        name: "Roma",
        number: "15",
        pts: 15,
        fg: "3-6",
        threePt: "0-2",
        ft: "2-4",
        reb: 9,
        ast: 8,
        to: 4,
        stl: 3,
        blk: 0,
        oreb: 5,
        dreb: 10,
        pf: 2,
        min: 26,
        plusMinus: -8,
      },
    ],
    totals: {
      pts: 99,
      fg: "39-88",
      threePt: "8-23",
      ft: "15-20",
      reb: 45,
      ast: 23,
      to: 18,
      stl: 12,
      blk: 0,
      oreb: 12,
      dreb: 33,
      pf: 33,
      min: 240,
      fgPct: 44,
      threePtPct: 29,
      ftPct: 65,
    },
  },
  {
    teamName: "Chicago Bulls",
    teamLogo: "/Bulls.png",
    starters: [
      {
        name: "Precious Achiuwa",
        number: "15",
        pts: 15,
        fg: "3-6",
        threePt: "0-2",
        ft: "2-4",
        reb: 9,
        ast: 6,
        to: 4,
        stl: 3,
        blk: 0,
        oreb: 5,
        dreb: 10,
        pf: 2,
        min: 26,
        plusMinus: -8,
      },
      {
        name: "Drew Eubanks",
        number: "15",
        pts: 15,
        fg: "3-6",
        threePt: "0-2",
        ft: "2-4",
        reb: 9,
        ast: 6,
        to: 4,
        stl: 3,
        blk: 0,
        oreb: 5,
        dreb: 10,
        pf: 2,
        min: 26,
        plusMinus: -8,
      },
      {
        name: "Russell Westbrook",
        number: "15",
        pts: 15,
        fg: "3-6",
        threePt: "0-2",
        ft: "2-4",
        reb: 9,
        ast: 6,
        to: 4,
        stl: 3,
        blk: 0,
        oreb: 5,
        dreb: 10,
        pf: 2,
        min: 26,
        plusMinus: -8,
      },
      {
        name: "DeMar DeRozan",
        number: "15",
        pts: 15,
        fg: "3-6",
        threePt: "0-2",
        ft: "2-4",
        reb: 9,
        ast: 6,
        to: 4,
        stl: 3,
        blk: 0,
        oreb: 5,
        dreb: 10,
        pf: 2,
        min: 26,
        plusMinus: -8,
      },
      {
        name: "Zach LaVine",
        number: "15",
        pts: 15,
        fg: "3-6",
        threePt: "0-2",
        ft: "2-4",
        reb: 9,
        ast: 6,
        to: 4,
        stl: 3,
        blk: 0,
        oreb: 5,
        dreb: 10,
        pf: 2,
        min: 26,
        plusMinus: -8,
      },
    ],
    bench: [
      {
        name: "Roma",
        number: "15",
        pts: 15,
        fg: "3-6",
        threePt: "0-2",
        ft: "2-4",
        reb: 9,
        ast: 8,
        to: 4,
        stl: 3,
        blk: 0,
        oreb: 5,
        dreb: 10,
        pf: 2,
        min: 26,
        plusMinus: -8,
      },
      {
        name: "Roma",
        number: "15",
        pts: 15,
        fg: "3-6",
        threePt: "0-2",
        ft: "2-4",
        reb: 9,
        ast: 8,
        to: 4,
        stl: 3,
        blk: 0,
        oreb: 5,
        dreb: 10,
        pf: 2,
        min: 26,
        plusMinus: -8,
      },
      {
        name: "Roma",
        number: "15",
        pts: 15,
        fg: "3-6",
        threePt: "0-2",
        ft: "2-4",
        reb: 9,
        ast: 8,
        to: 4,
        stl: 3,
        blk: 0,
        oreb: 5,
        dreb: 10,
        pf: 2,
        min: 26,
        plusMinus: -8,
      },
      {
        name: "Roma",
        number: "15",
        pts: 15,
        fg: "3-6",
        threePt: "0-2",
        ft: "2-4",
        reb: 9,
        ast: 8,
        to: 4,
        stl: 3,
        blk: 0,
        oreb: 5,
        dreb: 10,
        pf: 2,
        min: 26,
        plusMinus: -8,
      },
    ],
    totals: {
      pts: 99,
      fg: "39-88",
      threePt: "8-23",
      ft: "15-20",
      reb: 45,
      ast: 23,
      to: 18,
      stl: 12,
      blk: 0,
      oreb: 12,
      dreb: 33,
      pf: 33,
      min: 240,
      fgPct: 44,
      threePtPct: 29,
      ftPct: 65,
    },
  },
]
  return (
    <div className='w-full space-y-3 pb-28 lg:pb-10'>
        <div className='py-4 lg:py-0'>
         <DetailsImageCard competitionCountry='USA' competitionName='NBA' hostTeamName='Detroit Pistons' hostTeamLogo='/Pistons.png' matchStatus='finished' hostTeamScore={121} guestTeamScore={131} guestTeamLogo='/Bulls.png' guestTeamName='Chicago Bulls'/>
        </div>
        <div className='w-full'>
          <BasketBallScoreCard team1={{
              name: 'Detroit Pistons',
              quarterScores: [28, 30, 26, 26],
              total: 122,

            }}
            team2={{
              name: 'Chicago Bulls',
              quarterScores: [30, 28, 24, 28],
              total: 120,
            
            }}
            quarters={[
              { id: 'q1', label: 'Q1' },
              { id: 'q2', label: 'Q2' },
              { id: 'q3', label: 'Q3' },
              { id: 'q4', label: 'Q4' }
            ]}/>
        </div>
        <div className='w-full'>
          <VenueGuide/>
        </div>
        <div className="w-full mx-auto">
          <TeamStats teams={sampleTeams}/>
        </div>
        <div><ImportantUpdate/></div>
    </div>
  )
}

export default BasketBallDetailsPage