worker_processes auto;

env BROADAGE_API_KEY;
env PROXY_SECRET;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/json;

    server_tokens off;
    sendfile on;

    log_format main '$remote_addr [$time_local] "$request" '
                    '$status $body_bytes_sent';

    access_log /var/log/nginx/access.log main;
    error_log  /var/log/nginx/error.log warn;

    include /etc/nginx/conf.d/*.conf;
}
